version: "3.3"
services:
  api:
    container_name: tqs-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  react:
    container_name: tqs-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      API_HOST: api
